INSERT INTO Card
(Name, Subname, Type, IsFoil, IsBorderless, Price, Cost, Strength, Willpower, Release)
VALUES
('Elsa', 'Spirit of Winter', 'Character', 1, 1, 500.00, 8, 4, 6, 'The First Chapter'),
('Belle', 'Strange but Special', 'Character', 1, 1, 250.00, 4, 2, 4, 'The First Chapter'),
('Tinker Bell', 'Giant Fairy', 'Character', 1, 1, 250.00, 6, 4, 5, 'The First Chapter'),
('Aladdin', 'Heroic Outlaw', 'Character', 1, 1, 200.00, 7, 5, 5, 'The First Chapter'),
('Genie', 'On the Job', 'Character', 1, 1, 200.00, 7, 5, 5, 'The First Chapter'),
('Mickey Mouse', 'Wayward Sorcerer', 'Character', 1, 1, 200.00, 4, 3, 4, 'The First Chapter'),
('Simba', 'Returned King', 'Character', 1, 1, 200.00, 7, 4, 6, 'The First Chapter'),
('Stitch', 'Carefree Surfer', 'Character', 1, 1, 200.00, 7, 4, 8, 'The First Chapter'),
('Aurora', 'Dreaming Guardian', 'Character', 1, 1, 175.00, 5, 3, 5, 'The First Chapter'),
('Hades', 'King of Olympus', 'Character', 1, 1, 175.00, 8, 6, 7, 'The First Chapter'),
('Mickey Mouse', 'Artful Rogue', 'Character', 1, 1, 175.00, 7, 6, 5, 'The First Chapter'),
('Maui', 'Hero to All', 'Character', 1, 1, 150.00, 5, 6, 5, 'The First Chapter'),
('Rapunzel', 'Gifted with Healing', 'Character', 1, 0, 110.00, 4, 1, 5, 'The First Chapter'),
('Stitch', 'Carefree Surfer', 'Character', 1, 0, 80.00, 7, 4, 8, 'The First Chapter'),
('Belle', 'Strange but Special', 'Character', 1, 0, 70.00, 4, 2, 4, 'The First Chapter'),
('Maleficent', 'Monstrous Dragon', 'Character', 1, 0, 70.00, 9, 7, 5, 'The First Chapter'),
('Elsa', 'Spirit of Winter', 'Character', 1, 0, 70.00, 8, 4, 6, 'The First Chapter'),
('Hades', 'Infernal Schemer', 'Character', 1, 0, 50.00, 7, 3, 6, 'The First Chapter'),
('John Silver', 'Alien Pirate', 'Character', 1, 0, 50.00, 6, 5, 5, 'The First Chapter'),
('Mickey Mouse', 'Brave Little Tailor', 'Character', 1, 0, 40.00, 8, 5, 5, 'The First Chapter'),
('Tinker Bell', 'Giant Fairy', 'Character', 1, 0, 30.00, 6, 4, 5, 'The First Chapter'),
('Ursula', 'Power Hungry', 'Character', 1, 0, 30.00, 7, 2, 8, 'The First Chapter'),
('A Whole New World', NULL, 'Action', 1, 0, 25.00, 5, NULL, NULL, 'The First Chapter'),
('Befuddle', NULL, 'Action', 1, 0, 25.00, 1, NULL, NULL, 'The First Chapter'),
('Stitch', 'Rock Star', 'Character', 1, 0, 25.00, 6, 3, 5, 'The First Chapter'),
('Kuzco', 'Temperamental Emperor', 'Character', 1, 0, 20.00, 5, 2, 4, 'The First Chapter'),
('Lilo', 'Making a Wish', 'Character', 1, 0, 20.00, 1, 1, 1, 'The First Chapter'),
('Ariel', 'Spectacular Singer', 'Character', 1, 0, 15.00, 3, 2, 3, 'The First Chapter'),
('Te Kā', 'Heartless', 'Character', 1, 0, 15.00, 6, 5, 5, 'The First Chapter'),
('Be Prepared', NULL, 'Action', 1, 0, 15.00, 7, NULL, NULL, 'The First Chapter'),
('Beast', 'Wolfsbane', 'Character', 1, 0, 15.00, 5, 4, 4, 'The First Chapter'),
('Gantu', 'Galactic Federation', 'Character', 1, 0, 12.00, 8, 6, 6, 'The First Chapter'),
('Maui', 'Hero to All', 'Character', 1, 0, 12.00, 5, 6, 5, 'The First Chapter'),
('Let It Go', NULL, 'Action', 1, 0, 12.00, 5, NULL, NULL, 'The First Chapter'),
('Lantern', NULL, 'Item', 1, 0, 10.00, 2, NULL, NULL, 'The First Chapter'),
('The Queen', 'Wicked and Vain', 'Character', 1, 0, 10.00, 5, 4, 5, 'The First Chapter'),
('Grab Your Sword', NULL, 'Action', 1, 0, 10.00, 5, NULL, NULL, 'The First Chapter'),
('Hans', 'Scheming Prince', 'Character', 1, 0, 10.00, 4, 3, 3, 'The First Chapter'),
('Chief Tui', 'Respected Leader', 'Character', 1, 0, 10.00, 7, 3, 6, 'The First Chapter'),
('Mother Gothel', 'Selfisch Manipulator', 'Character', 1, 0, 8.00, 6, 3, 6, 'The First Chapter'),
('Robin Hood', 'Unrivaled Archer', 'Character', 1, 0, 8.00, 6, 4, 4, 'The First Chapter'),
('Fishbone Quill', NULL, 'Item', 1, 0, 8.00, 3, NULL, NULL, 'The First Chapter'),
('Maleficent', 'Biding Her Time', 'Character', 1, 0, 8.00, 1, 1, 1, 'The First Chapter'),
('Maximus', 'Palace Horse', 'Character', 1, 0, 8.00, 5, 4, 5, 'The First Chapter'),
('Genie', 'On the Job', 'Character', 1, 0, 8.00, 6, 3, 4, 'The First Chapter'),
('Hans', 'Thirteenth in Line', 'Character', 1, 0, 8.00, 4, 3, 3, 'The First Chapter'),
('Jasmine', 'Queen of Agrabah', 'Character', 1, 0, 6.00, 5, 2, 5, 'The First Chapter'),
('Just In Time', NULL, 'Action', 1, 0, 6.00, 3, NULL, NULL, 'The First Chapter'),
('Magic Mirror', NULL, 'Item', 1, 0, 6.00, 2, NULL, NULL, 'The First Chapter'),
('Mickey Mouse', 'Wayward Sorcerer', 'Character', 1, 0, 6.00, 4, 3, 4, 'The First Chapter'),
('Aurora', 'Dreaming Guardian', 'Character', 1, 0, 6.00, 5, 3, 5, 'The First Chapter'),
('Hades', 'Lord of the Underworld', 'Character', 1, 0, 6.00, 4, 3, 2, 'The First Chapter'),
('Tamatoa', 'So Shiny!', 'Character', 1, 0, 6.00, 8, 5, 8, 'The First Chapter'),
('Aladdin', 'Heroic Outlaw', 'Character', 1, 0, 6.00, 7, 5, 5, 'The First Chapter'),
('Work Together', NULL, 'Action', 1, 0, 5.00, 1, NULL, NULL, 'The First Chapter'),
('Merlin', 'Self-Appointed Mentor', 'Character', 1, 0, 5.00, 4, 3, 4, 'The First Chapter'),
('Jafar', 'Keeper of Secrets', 'Character', 1, 0, 5.00, 4, 0, 5, 'The First Chapter'),
('If It"s Not Baroque', NULL, 'Action', 1, 0, 4.00, 3, NULL, NULL, 'The First Chapter'),
('Scar', 'Shameless Firebrand', 'Character', 1, 0, 4.00, 8, 6, 6, 'The First Chapter'),
('Cruella De Vil', 'Miserable as Usual', 'Character', 1, 0, 4.00, 2, 1, 3, 'The First Chapter'),
('Te Kā', 'The Burning One', 'Character', 1, 0, 4.00, 6, 8, 6, 'The First Chapter'),
('Zeus', 'God of Lightning', 'Character', 1, 0, 4.00, 4, 0, 4, 'The First Chapter'),
('Poisoned Apple', NULL, 'Item', 1, 0, 4.00, 3, NULL, NULL, 'The First Chapter'),
('Hades', 'King of Olympus', 'Character', 1, 0, 4.00, 8, 6, 7, 'The First Chapter'),
('Captain Hook', 'Thinking a Happy Thought', 'Character', 1, 0, 4.00, 5, 2, 5, 'The First Chapter'),
('Simba', 'Returned King', 'Character', 1, 0, 4.00, 7, 4, 6, 'The First Chapter'),
('Flotsam', 'Ursula"s Spy', 'Character', 1, 0, 4.00, 5, 3, 4, 'The First Chapter'),
('Plasma Blaster', NULL, 'Item', 1, 0, 4.00, 3, NULL, NULL, 'The First Chapter'),
('Iago', 'Loud-Mouthed Parrot', 'Character', 1, 0, 4.00, 3, 1, 4, 'The First Chapter'),
('Dr. Facilier', 'Agent Provocateur', 'Character', 1, 0, 4.00, 7, 4, 5, 'The First Chapter'),
('Mickey Mouse', 'Artful Rogue', 'Character', 1, 0, 4.00, 7, 6, 5, 'The First Chapter'),
('Ursula"s Shell Necklace', NULL, 'Item', 1, 0, 4.00, 3, NULL, NULL, 'The First Chapter'),
('Scar', 'Mastermind', 'Character', 1, 0, 4.00, 6, 5, 4, 'The First Chapter'),
('Lefou', 'Instigator', 'Character', 1, 0, 4.00, 2, 2, 2, 'The First Chapter'),
('Do It Again!', NULL, 'Action', 1, 0, 4.00, 3, NULL, NULL, 'The First Chapter'),
('Stitch', 'Abomination', 'Character', 1, 0, 4.00, 6, 4, 6, 'The First Chapter'),
('Captain Hook', 'Captain of the Jolly Roger', 'Character', 1, 0, 4.00, 4, 3, 4, 'The First Chapter'),
('Maurice', 'World-Famous Inventor', 'Character', 1, 0, 4.00, 6, 2, 7, 'The First Chapter'),
('Genie', 'Powers Unleashed', 'Character', 1, 0, 4.00, 8, 3, 5, 'The First Chapter'),
('White Rabbit"s Pocket Watch', NULL, 'Item', 1, 0, 4.00, 3, NULL, NULL, 'The First Chapter'),
('Part Of Your World', NULL, 'Action', 1, 0, 4.00, 3, NULL, NULL, 'The First Chapter'),
('Mickey Mouse', 'Musketeer', 'Character', 1, 0, 4.00, 6, 2, 7, 'The First Chapter'),
('Steal From The Rich', NULL, 'Action', 1, 0, 4.00, 5, NULL, NULL, 'The First Chapter'),
('Marshmallow', 'Persistent Guardian', 'Character', 1, 0, 4.00, 6, 5, 5, 'The First Chapter'),
('Ariel', 'Whoseit Collector', 'Character', 1, 0, 4.00, 4, 3, 3, 'The First Chapter'),
('Moana', 'Of Motunui', 'Character', 1, 0, 4.00, 5, 1, 6, 'The First Chapter'),
('Mulan', 'Imperial Soldier', 'Character', 1, 0, 4.00, 5, 4, 5, 'The First Chapter'),
('Sword Of Truth', NULL, 'Item', 1, 0, 4.00, 4, NULL, NULL, 'The First Chapter'),
('Lady Tremaine', 'Wicked Stepmother', 'Character', 1, 0, 4.00, 6, 1, 5, 'The First Chapter'),
('Captain Hook', 'Ruthless Pirate', 'Character', 1, 0, 4.00, 7, 5, 5, 'The First Chapter'),
('Musketeer Tabard', NULL, 'Item', 1, 0, 4.00, 4, NULL, NULL, 'The First Chapter'),
('Maleficent', 'Uninvited', 'Character', 1, 0, 4.00, 5, 3, 6, 'The First Chapter'),
('Dr. Facilier', 'Remarkable Gentleman', 'Character', 1, 0, 4.00, 3, 2, 4, 'The First Chapter'),
('Maui', 'Demigod', 'Character', 1, 0, 4.00, 8, 8, 8, 'The First Chapter'),
('Flynn Rider', 'Charming Rogue', 'Character', 1, 0, 3.00, 2, 1, 2, 'The First Chapter'),
('Cheshire Cat', 'Not All There', 'Character', 1, 0, 2.00, 3, 0, 3, 'The First Chapter'),
('Elsa', 'Snow Queen', 'Character', 1, 0, 2.00, 3, 2, 3, 'The First Chapter'),
('Eye Of The Fates', NULL, 'Item', 1, 0, 1.50, 4, NULL, NULL, 'The First Chapter'),
('Lefou', 'Bumbler', 'Character', 1, 0, 0.75, 2, 1, 2, 'The First Chapter'),
('You Have Forgotten Me', NULL, 'Action', 1, 0, 0.75, 4, NULL, NULL, 'The First Chapter'),
('Moana', 'Chosen by the Ocean', 'Character', 1, 0, 0.75, 5, 2, 6, 'The First Chapter'),
('Frying Pan', NULL, 'Item', 1, 0, 0.75, 2, NULL, NULL, 'The First Chapter'),
('Ursula"s Cauldron', Null, 'Item', 1, 0, 0.75, 2, NULL, NULL, 'The First Chapter'),
('Prince Phillip', 'Dragonslayer', 'Character', 1, 0, 0.75, 4, 3, 3, 'The First Chapter'),
('Be Our Guest', NULL, 'Action', 1, 0, 0.75, 2, NULL, NULL, 'The First Chapter'),
('Goofy', 'Musketeer', 'Character', 1, 0, 0.75, 5, 3, 6, 'The First Chapter'),
('One Jump Ahead', NULL, 'Action', 1, 0, 0.75, 2, NULL, NULL, 'The First Chapter'),
('Olaf', 'Friendly Snowman', 'Character', 1, 0, 0.75, 1, 1, 3, 'The First Chapter'),
('Ariel', 'On Human Legs', 'Character', 1, 0, 0.75, 4, 3, 4, 'The First Chapter'),
('Rafiki', 'Mysterious Sage', 'Character', 1, 0, 0.75, 3, 3, 3, 'The First Chapter'),
('Ransack', NULL, 'Action', 1, 0, 0.75, 2, NULL, NULL, 'The First Chapter'),
('Mickey Mouse', 'True Friend', 'Character', 1, 0, 0.75, 3, 3, 3, 'The First Chapter'),
('Beast', 'Hardheaded', 'Character', 1, 0, 0.75, 5, 4, 4, 'The First Chapter'),
('Cut To The Chase', NULL, 'Action', 1, 0, 0.75, 2, NULL, NULL, 'The First Chapter'),
('Triton', 'The Sea King', 'Character', 1, 0, 0.75, 7, 5, 9, 'The First Chapter'),
('Belle', 'Inventive Engineer', 'Character', 1, 0, 0.75, 3, 2, 3, 'The First Chapter'),
('Jumba Jookiba', 'Renegade', 'Character', 1, 0, 0.75, 5, 4, 5, 'The First Chapter'),
('Gramma Tala', 'Storyteller', 'Character', 1, 0, 0.75, 2, 1, 1, 'The First Chapter'),
('Smash', NULL, 'Action', 1, 0, 0.75, 3, NULL, NULL, 'The First Chapter'),
('Rapunzel', 'Letting Down Her Hair', 'Character', 1, 0, 0.75, 6, 5, 4, 'The First Chapter'),
('Lilo', 'Galactic Hero', 'Character', 1, 0, 0.75, 3, 4, 2, 'The First Chapter'),
('Pascal', 'Rapunzel"s Companion', 'Character', 1, 0, 0.75, 1, 1, 1, 'The First Chapter'),
('Donald Duck', 'Boisterous Fowl', 'Character', 1, 0, 0.75, 2, 2, 3, 'The First Chapter'),
('Mad Hatter', 'Gracious Host', 'Character', 1, 0, 0.75, 5, 2, 4, 'The First Chapter'),
('Simba', 'Rightful Heir', 'Character', 1, 0, 0.75, 5, 3, 5, 'The First Chapter'),
('Sven', 'Official Ice Deliverer', 'Character', 1, 0, 0.75, 6, 5, 7, 'The First Chapter'),
('Coconut Basket', NULL, 'Item', 1, 0, 0.75, 2, NULL, NULL, 'The First Chapter'),
('Captain', 'Colonel"s Lieutenant', 'Character', 1, 0, 0.75, 5, 6, 5, 'The First Chapter'),
('Jasper', 'Common Crook', 'Character', 1, 0, 0.75, 3, 2, 4, 'The First Chapter'),
('Kronk', 'Right-Hand Man', 'Character', 1, 0, 0.75, 6, 6, 6, 'The First Chapter'),
('Starkey', 'Hook"s Henchman', 'Character', 1, 0, 0.75, 5, 5, 4, 'The First Chapter'),
('Reflection', NULL, 'Action', 1, 0, 0.75, 1, NULL, NULL, 'The First Chapter'),
('Dr. Facilier"s Cards', NULL, 'Item', 1, 0, 0.75, 2, NULL, NULL, 'The First Chapter'),
('Shield Of Virtue', NULL, 'Item', 1, 0, 0.75, 1, NULL, NULL, 'The First Chapter'),
('Donald Duck', 'Musketeer', 'Character', 1, 0, 0.75, 4, 2, 5, 'The First Chapter'),
('Tigger', 'Wonderful Thing', 'Character', 1, 0, 0.75, 6, 4, 4, 'The First Chapter'),
('Cinderella', 'Gentle and Kind', 'Character', 1, 0, 0.75, 4, 2, 5, 'The First Chapter'),
('Dragon Fire', NULL, 'Action', 1, 0, 0.75, 5, NULL, NULL, 'The First Chapter'),
('Mother Knows best', NULL, 'Action', 1, 0, 0.75, 3, NULL, NULL, 'The First Chapter'),
('Maximus', 'Relentless Pursuer', 'Character', 1, 0, 0.75, 3, 3, 3, 'The First Chapter'),
('Tamatoa', 'Drab Little Crab', 'Character', 1, 0, 0.75, 2, 1, 4, 'The First Chapter'),
('The Beast Is Mine!', NULL, 'Action', 1, 0, 0.75, 3, NULL, NULL, 'The First Chapter'),
('Anna', 'Heir to Arendelle', 'Character', 1, 0, 0.75, 4, 2, 4, 'The First Chapter'),
('Fan The Flames', NULL, 'Action', 1, 0, 0.75, 1, NULL, NULL, 'The First Chapter'),
('Aurora', 'Regal Princess', 'Character', 1, 0, 0.75, 2, 2, 2, 'The First Chapter'),
('Scepter Of Arendelle', NULL, 'Item', 1, 0, 0.75, 1, NULL, NULL, 'The First Chapter'),
('Scar', 'Fiery Usurper', 'Character', 1, 0, 0.50, 4, 5, 3, 'The First Chapter'),
('Sebastian', 'Court Composer', 'Character', 1, 0, 0.50, 2, 2, 2, 'The First Chapter'),
('Magic Broom', 'Bucket Brigade', 'Character', 1, 0, 0.50, 2, 2, 2, 'The First Chapter'),
('Peter Pan', 'Never Landing', 'Character', 1, 0, 0.50, 3, 3, 2, 'The First Chapter'),
('Mr. Smee', 'Loyal First Mate', 'Character', 1, 0, 0.50, 3, 2, 5, 'The First Chapter'),
('Jasmine', 'Disguised', 'Character', 1, 0, 0.50, 3, 3, 3, 'The First Chapter'),
('Tinker Bell', 'Tiny Tactician', 'Character', 1, 0, 0.50, 3, 2, 4, 'The First Chapter'),
('Tinker Bell', 'Peter Pan"s Ally', 'Character', 1, 0, 0.50, 5, 3, 3, 'The First Chapter'),
('Minnie Mouse', 'Beloved Princess', 'Character', 1, 0, 0.50, 2, 2, 3, 'The First Chapter'),
('Jetsam', 'Ursula"s Spy', 'Character', 1, 0, 0.50, 4, 3, 3, 'The First Chapter'),
('Stolen Scimitar', NULL, 'Item', 1, 0, 0.50, 2, NULL, NULL, 'The First Chapter'),
('Tangle', NULL, 'Action', 1, 0, 0.50, 2, NULL, NULL, 'The First Chapter'),
('The Wardrobe', 'Belle"s Confidant', 'Character', 1, 0, 0.50, 3, 3, 4, 'The First Chapter'),
('Prince Eric', 'Dashing and Brave', 'Character', 1, 0, 0.50, 2, 1, 3, 'The First Chapter'),
('Maleficent', 'Sinister Visitor', 'Character', 1, 0, 0.50, 4, 3, 4, 'The First Chapter'),
('Abu', 'Mischievous Monkey', 'Character', 1, 0, 0.50, 3, 3, 2, 'The First Chapter'),
('Megara', 'Pulling the Strings', 'Character', 1, 0, 0.50, 2, 2, 1, 'The First Chapter'),
('Break', NULL, 'Action', 1, 0, 0.50, 2, NULL, NULL, 'The First Chapter'),
('Aladdin', 'Street Rat', 'Character', 1, 0, 0.50, 3, 2, 2, 'The First Chapter'),
('Beast"s Mirror', NULL, 'Item', 1, 0, 0.50, 2, NULL, NULL, 'The First Chapter'),
('Control Your Temper!', NULL, 'Action', 1, 0, 0.50, 1, NULL, NULL, 'The First Chapter'),
('Magic Golden Flower', NULL, 'Item', 1, 0, 0.50, 1, NULL, NULL, 'The First Chapter'),
('Stitch', 'New Dog', 'Character', 1, 0, 0.50, 1, 2, 2, 'The First Chapter'),
('Sergeant Tibbs', 'Courageous Cat', 'Character', 1, 0, 0.50, 1, 2, 2, 'The First Chapter'),
('Develop Your Brain', NULL, 'Action', 1, 0, 0.50, 1, NULL, NULL, 'The First Chapter'),
('Healing Glow', NULL, 'Action', 1, 0, 0.50, 1, NULL, NULL, 'The First Chapter'),
('Stampede', NULL, 'Action', 1, 0, 0.50, 1, NULL, NULL, 'The First Chapter'),
('Sudden Chill', NULL, 'Action', 1, 0, 0.50, 2, NULL, NULL, 'The First Chapter'),
('Donald Duck', 'Strutting His Stuff', 'Character', 1, 0, 0.50, 5, 4, 3, 'The First Chapter'),
('Tinker Bell', 'Most Helpful', 'Character', 1, 0, 0.50, 4, 2, 3, 'The First Chapter'),
('Fire The Cannons', NULL, 'Action', 1, 0, 0.50, 1, NULL, NULL, 'The First Chapter'),
('Hankuna Matata', NULL, 'Action', 1, 0, 0.50, 4, NULL, NULL, 'The First Chapter'),
('Aladdin', 'Prince Ali', 'Character', 1, 0, 0.50, 2, 2, 2, 'The First Chapter'),
('Horace', 'No-Good Scoundrel', 'Character', 1, 0, 0.50, 3, 4, 3, 'The First Chapter'),
('Minnie Mouse', 'Always Classy', 'Character', 1, 0, 0.50, 1, 1, 3, 'The First Chapter'),
('Kristoff', 'Official Ice Master', 'Character', 1, 0, 0.50, 3, 3, 3, 'The First Chapter'),
('He"s Got A Sword', NULL, 'Action', 1, 0, 0.50, 1, NULL, NULL, 'The First Chapter'),
('Aladdin', 'Cornered Swordsman', 'Character', 1, 0, 0.50, 2, 2, 1, 'The First Chapter'),
('Jafar', 'Wicked Sorcerer', 'Character', 1, 0, 0.50, 4, 2, 5, 'The First Chapter'),
('Maleficent', 'Sorceress', 'Character', 1, 0, 0.50, 3, 2, 2, 'The First Chapter'),
('Friends On The Other Side', NULL, 'Action', 1, 0, 0.50, 3, NULL, NULL, 'The First Chapter'),
('Goofy', 'Daredevil', 'Character', 1, 0, 0.50, 5, 3, 4, 'The First Chapter'),
('Dr. Facilier', 'Charlatan', 'Character', 1, 0, 0.50, 2, 0, 4, 'The First Chapter'),
('Captain Hook', 'Forceful Duelist', 'Character', 1, 0, 0.50, 1, 1, 2, 'The First Chapter'),
('Pumbaa', 'Friendly Warthog', 'Character', 1, 0, 0.50, 4, 3, 5, 'The First Chapter'),
('Elsa', 'Queen Regent', 'Character', 1, 0, 0.50, 4, 4, 4, 'The First Chapter'),
('Genie', 'The Ever Impressive', 'Character', 1, 0, 0.50, 2, 2, 3, 'The First Chapter'),
('Simba', 'Future King', 'Character', 1, 0, 0.50, 1, 1, 2, 'The First Chapter'),
('Archimedes', 'Highly Educated Owl', 'Character', 1, 0, 0.50, 1, 2, 2, 'The First Chapter'),
('Goons', 'Maleficent"s Underlings', 'Character', 1, 0, 0.50, 1, 2, 2, 'The First Chapter'),
('Flounder', 'Voice of Reason', 'Character', 1, 0, 0.50, 1, 2, 2, 'The First Chapter'),
('Hercules', 'True Hero', 'Character', 1, 0, 0.50, 3, 3, 3, 'The First Chapter'),
('Pongo', 'Ol" Rascal', 'Character', 1, 0, 0.50, 4, 2, 3, 'The First Chapter'),
('Heihei', 'Boat Snack', 'Character', 1, 0, 0.50, 1, 1, 2, 'The First Chapter'),
('Vicious Betrayal', NULL, 'Action', 1, 0, 0.50, 1, NULL, NULL, 'The First Chapter'),
('Timon', 'Grub Rustler', 'Character', 1, 0, 0.50, 1, 1, 2, 'The First Chapter'),
('Simba', 'Protective Cub', 'Character', 1, 0, 0.50, 2, 2, 3, 'The First Chapter'),
('Mickey Mouse', 'Detective', 'Character', 1, 0, 0.50, 3, 1, 3, 'The First Chapter'),
('Duke Of Weselton', 'Opportunistic Official', 'Character', 1, 0, 0.50, 1, 2, 2, 'The First Chapter'),
('Elsa', 'Ice Surfer', 'Character', 1, 0, 0.50, 4, 3, 4, 'The First Chapter'),
('Philoctetes', 'Trainer of Heroes', 'Character', 1, 0, 0.50, 2, 3, 1, 'The First Chapter'),
('Gaston', 'Arrogant Hunter', 'Character', 1, 0, 0.50, 1, 1, 1, 'The First Chapter'),
('Cerberus', 'Three-Headed Dog', 'Character', 1, 0, 0.50, 5, 5, 6, 'The First Chapter'),
('Peter Pan', 'Fearless Fighter', 'Character', 1, 0, 0.50, 3, 3, 2, 'The First Chapter'),
('Aurora', 'Briar Rose', 'Character', 1, 0, 0.50, 4, 2, 5, 'The First Chapter'),
('Mufasa', 'King of the Pride', 'Character', 1, 0, 0.50, 6, 4, 6, 'The First Chapter'),
('Ymza', 'Alchemist', 'Character', 1, 0, 0.50, 2, 2, 2, 'The First Chapter'),
('Freeze', NULL, 'Action', 1, 0, 0.50, 2, NULL, NULL, 'The First Chapter'),
('Dinglehopper', NULL, 'Item', 1, 0, 0.50, 1, NULL, NULL, 'The First Chapter'),
('Mickey Mouse', 'Steamboat Pilot', 'Character', 1, 0, 0.50, 3, 3, 4, 'The First Chapter'),
('Rapunzel', 'Gifted with Healing', 'Character', 0, 0, 55.00, 4, 1, 5, 'The First Chapter'),
('Stitch', 'Carefree Surfer', 'Character', 0, 0, 40.00, 7, 4, 8, 'The First Chapter'),
('Belle', 'Strange but Special', 'Character', 0, 0, 35.00, 4, 2, 4, 'The First Chapter'),
('Maleficent', 'Monstrous Dragon', 'Character', 0, 0, 35.00, 9, 7, 5, 'The First Chapter'),
('Elsa', 'Spirit of Winter', 'Character', 0, 0, 35.00, 8, 4, 6, 'The First Chapter'),
('Hades', 'Infernal Schemer', 'Character', 0, 0, 25.00, 7, 3, 6, 'The First Chapter'),
('John Silver', 'Alien Pirate', 'Character', 0, 0, 25.00, 6, 5, 5, 'The First Chapter'),
('Mickey Mouse', 'Brave Little Tailor', 'Character', 0, 0, 20.00, 8, 5, 5, 'The First Chapter'),
('Tinker Bell', 'Giant Fairy', 'Character', 0, 0, 15.00, 6, 4, 5, 'The First Chapter'),
('Ursula', 'Power Hungry', 'Character', 0, 0, 15.00, 7, 2, 8, 'The First Chapter'),
('A Whole New World', NULL, 'Action', 0, 0, 12.00, 5, NULL, NULL, 'The First Chapter'),
('Befuddle', NULL, 'Action', 0, 0, 0.50, 1, NULL, NULL, 'The First Chapter'),
('Stitch', 'Rock Star', 'Character', 0, 0, 12.00, 6, 3, 5, 'The First Chapter'),
('Kuzco', 'Temperamental Emperor', 'Character', 0, 0, 10.00, 5, 2, 4, 'The First Chapter'),
('Lilo', 'Making a Wish', 'Character', 0, 0, 10.00, 1, 1, 1, 'The First Chapter'),
('Ariel', 'Spectacular Singer', 'Character', 0, 0, 8.00, 3, 2, 3, 'The First Chapter'),
('Te Kā', 'Heartless', 'Character', 0, 0, 8.00, 6, 5, 5, 'The First Chapter'),
('Be Prepared', NULL, 'Action', 0, 0, 8.00, 7, NULL, NULL, 'The First Chapter'),
('Beast', 'Wolfsbane', 'Character', 0, 0, 8.00, 5, 4, 4, 'The First Chapter'),
('Gantu', 'Galactic Federation', 'Character', 0, 0, 6.00, 8, 6, 6, 'The First Chapter'),
('Maui', 'Hero to All', 'Character', 0, 0, 6.00, 5, 6, 5, 'The First Chapter'),
('Let It Go', NULL, 'Action', 0, 0, 8.00, 5, NULL, NULL, 'The First Chapter'),
('Lantern', NULL, 'Item', 0, 0, 5.00, 2, NULL, NULL, 'The First Chapter'),
('The Queen', 'Wicked and Vain', 'Character', 0, 0, 5.00, 5, 4, 5, 'The First Chapter'),
('Grab Your Sword', NULL, 'Action', 0, 0, 5.00, 5, NULL, NULL, 'The First Chapter'),
('Hans', 'Scheming Prince', 'Character', 0, 0, 5.00, 4, 3, 3, 'The First Chapter'),
('Chief Tui', 'Respected Leader', 'Character', 0, 0, 0.50, 7, 3, 6, 'The First Chapter'),
('Mother Gothel', 'Selfisch Manipulator', 'Character', 0, 0, 4.00, 6, 3, 6, 'The First Chapter'),
('Robin Hood', 'Unrivaled Archer', 'Character', 0, 0, 4.00, 6, 4, 4, 'The First Chapter'),
('Fishbone Quill', NULL, 'Item', 0, 0, 4.00, 3, NULL, NULL, 'The First Chapter'),
('Maleficent', 'Biding Her Time', 'Character', 0, 0, 4.00, 1, 1, 1, 'The First Chapter'),
('Maximus', 'Palace Horse', 'Character', 0, 0, 4.00, 5, 4, 5, 'The First Chapter'),
('Genie', 'On the Job', 'Character', 0, 0, 4.00, 6, 3, 4, 'The First Chapter'),
('Hans', 'Thirteenth in Line', 'Character', 0, 0, 4.00, 4, 3, 3, 'The First Chapter'),
('Jasmine', 'Queen of Agrabah', 'Character', 0, 0, 3.00, 5, 2, 5, 'The First Chapter'),
('Just In Time', NULL, 'Action', 0, 0, 3.00, 3, NULL, NULL, 'The First Chapter'),
('Magic Mirror', NULL, 'Item', 0, 0, 3.00, 2, NULL, NULL, 'The First Chapter'),
('Mickey Mouse', 'Wayward Sorcerer', 'Character', 0, 0, 3.00, 4, 3, 4, 'The First Chapter'),
('Aurora', 'Dreaming Guardian', 'Character', 0, 0, 3.00, 5, 3, 5, 'The First Chapter'),
('Hades', 'Lord of the Underworld', 'Character', 0, 0, 3.00, 4, 3, 2, 'The First Chapter'),
('Tamatoa', 'So Shiny!', 'Character', 0, 0, 3.00, 8, 5, 8, 'The First Chapter'),
('Aladdin', 'Heroic Outlaw', 'Character', 0, 0, 3.00, 7, 5, 5, 'The First Chapter'),
('Work Together', NULL, 'Action', 0, 0, 0.25, 1, NULL, NULL, 'The First Chapter'),
('Merlin', 'Self-Appointed Mentor', 'Character', 0, 0, 0.25, 4, 3, 4, 'The First Chapter'),
('Jafar', 'Keeper of Secrets', 'Character', 0, 0, 3.00, 4, 0, 5, 'The First Chapter'),
('If It"s Not Baroque', NULL, 'Action', 0, 0, 2.00, 3, NULL, NULL, 'The First Chapter'),
('Scar', 'Shameless Firebrand', 'Character', 0, 0, 2.00, 8, 6, 6, 'The First Chapter'),
('Cruella De Vil', 'Miserable as Usual', 'Character', 0, 0, 2.00, 2, 1, 3, 'The First Chapter'),
('Te Kā', 'The Burning One', 'Character', 0, 0, 2.00, 6, 8, 6, 'The First Chapter'),
('Zeus', 'God of Lightning', 'Character', 0, 0, 2.00, 4, 0, 4, 'The First Chapter'),
('Poisoned Apple', NULL, 'Item', 0, 0, 2.00, 3, NULL, NULL, 'The First Chapter'),
('Hades', 'King of Olympus', 'Character', 0, 0, 2.00, 8, 6, 7, 'The First Chapter'),
('Captain Hook', 'Thinking a Happy Thought', 'Character', 0, 0, 2.00, 5, 2, 5, 'The First Chapter'),
('Simba', 'Returned King', 'Character', 0, 0, 2.00, 7, 4, 6, 'The First Chapter'),
('Flotsam', 'Ursula"s Spy', 'Character', 0, 0, 2.00, 5, 3, 4, 'The First Chapter'),
('Plasma Blaster', NULL, 'Item', 0, 0, 2.00, 3, NULL, NULL, 'The First Chapter'),
('Iago', 'Loud-Mouthed Parrot', 'Character', 0, 0, 2.00, 3, 1, 4, 'The First Chapter'),
('Dr. Facilier', 'Agent Provocateur', 'Character', 0, 0, 2.00, 7, 4, 5, 'The First Chapter'),
('Mickey Mouse', 'Artful Rogue', 'Character', 0, 0, 2.00, 7, 6, 5, 'The First Chapter'),
('Ursula"s Shell Necklace', NULL, 'Item', 0, 0, 2.00, 3, NULL, NULL, 'The First Chapter'),
('Scar', 'Mastermind', 'Character', 0, 0, 2.00, 6, 5, 4, 'The First Chapter'),
('Lefou', 'Instigator', 'Character', 0, 0, 2.00, 2, 2, 2, 'The First Chapter'),
('Do It Again!', NULL, 'Action', 0, 0, 2.00, 3, NULL, NULL, 'The First Chapter'),
('Stitch', 'Abomination', 'Character', 0, 0, 2.00, 6, 4, 6, 'The First Chapter'),
('Captain Hook', 'Captain of the Jolly Roger', 'Character', 0, 0, 2.00, 4, 3, 4, 'The First Chapter'),
('Maurice', 'World-Famous Inventor', 'Character', 0, 0, 2.00, 6, 2, 7, 'The First Chapter'),
('Genie', 'Powers Unleashed', 'Character', 0, 0, 2.00, 8, 3, 5, 'The First Chapter'),
('White Rabbit"s Pocket Watch', NULL, 'Item', 0, 0, 2.00, 3, NULL, NULL, 'The First Chapter'),
('Part Of Your World', NULL, 'Action', 0, 0, 2.00, 3, NULL, NULL, 'The First Chapter'),
('Mickey Mouse', 'Musketeer', 'Character', 0, 0, 2.00, 6, 2, 7, 'The First Chapter'),
('Steal From The Rich', NULL, 'Action', 0, 0, 2.00, 5, NULL, NULL, 'The First Chapter'),
('Marshmallow', 'Persistent Guardian', 'Character', 0, 0, 2.00, 6, 5, 5, 'The First Chapter'),
('Ariel', 'Whoseit Collector', 'Character', 0, 0, 2.00, 4, 3, 3, 'The First Chapter'),
('Moana', 'Of Motunui', 'Character', 0, 0, 2.00, 5, 1, 6, 'The First Chapter'),
('Mulan', 'Imperial Soldier', 'Character', 0, 0, 2.00, 5, 4, 5, 'The First Chapter'),
('Sword Of Truth', NULL, 'Item', 0, 0, 2.00, 4, NULL, NULL, 'The First Chapter'),
('Lady Tremaine', 'Wicked Stepmother', 'Character', 0, 0, 2.00, 6, 1, 5, 'The First Chapter'),
('Captain Hook', 'Ruthless Pirate', 'Character', 0, 0, 2.00, 7, 5, 5, 'The First Chapter'),
('Musketeer Tabard', NULL, 'Item', 0, 0, 2.00, 4, NULL, NULL, 'The First Chapter'),
('Maleficent', 'Uninvited', 'Character', 0, 0, 2.00, 5, 3, 6, 'The First Chapter'),
('Dr. Facilier', 'Remarkable Gentleman', 'Character', 0, 0, 2.00, 3, 2, 4, 'The First Chapter'),
('Maui', 'Demigod', 'Character', 0, 0, 2.00, 8, 8, 8, 'The First Chapter'),
('Flynn Rider', 'Charming Rogue', 'Character', 0, 0, 0.25, 2, 1, 2, 'The First Chapter'),
('Cheshire Cat', 'Not All There', 'Character', 0, 0, 1.00, 3, 0, 3, 'The First Chapter'),
('Elsa', 'Snow Queen', 'Character', 0, 0, 1.00, 3, 2, 3, 'The First Chapter'),
('Eye Of The Fates', NULL, 'Item', 0, 0, 1.00, 4, NULL, NULL, 'The First Chapter'),
('Lefou', 'Bumbler', 'Character', 0, 0, 0.35, 2, 1, 2, 'The First Chapter'),
('You Have Forgotten Me', NULL, 'Action', 0, 0, 0.35, 4, NULL, NULL, 'The First Chapter'),
('Moana', 'Chosen by the Ocean', 'Character', 0, 0, 0.35, 5, 2, 6, 'The First Chapter'),
('Frying Pan', NULL, 'Item', 0, 0, 0.35, 2, NULL, NULL, 'The First Chapter'),
('Ursula"s Cauldron', Null, 'Item', 0, 0, 0.35, 2, NULL, NULL, 'The First Chapter'),
('Prince Phillip', 'Dragonslayer', 'Character', 0, 0, 0.35, 4, 3, 3, 'The First Chapter'),
('Be Our Guest', NULL, 'Action', 0, 0, 0.35, 2, NULL, NULL, 'The First Chapter'),
('Goofy', 'Musketeer', 'Character', 0, 0, 0.35, 5, 3, 6, 'The First Chapter'),
('One Jump Ahead', NULL, 'Action', 0, 0, 0.35, 2, NULL, NULL, 'The First Chapter'),
('Olaf', 'Friendly Snowman', 'Character', 0, 0, 0.35, 1, 1, 3, 'The First Chapter'),
('Ariel', 'On Human Legs', 'Character', 0, 0, 0.35, 4, 3, 4, 'The First Chapter'),
('Rafiki', 'Mysterious Sage', 'Character', 0, 0, 0.35, 3, 3, 3, 'The First Chapter'),
('Ransack', NULL, 'Action', 0, 0, 0.35, 2, NULL, NULL, 'The First Chapter'),
('Mickey Mouse', 'True Friend', 'Character', 0, 0, 0.35, 3, 3, 3, 'The First Chapter'),
('Beast', 'Hardheaded', 'Character', 0, 0, 0.35, 5, 4, 4, 'The First Chapter'),
('Cut To The Chase', NULL, 'Action', 0, 0, 0.35, 2, NULL, NULL, 'The First Chapter'),
('Triton', 'The Sea King', 'Character', 0, 0, 0.35, 7, 5, 9, 'The First Chapter'),
('Belle', 'Inventive Engineer', 'Character', 0, 0, 0.35, 3, 2, 3, 'The First Chapter'),
('Jumba Jookiba', 'Renegade', 'Character', 0, 0, 0.35, 5, 4, 5, 'The First Chapter'),
('Gramma Tala', 'Storyteller', 'Character', 0, 0, 0.35, 2, 1, 1, 'The First Chapter'),
('Smash', NULL, 'Action', 0, 0, 0.35, 3, NULL, NULL, 'The First Chapter'),
('Rapunzel', 'Letting Down Her Hair', 'Character', 0, 0, 0.35, 6, 5, 4, 'The First Chapter'),
('Lilo', 'Galactic Hero', 'Character', 0, 0, 0.35, 3, 4, 2, 'The First Chapter'),
('Pascal', 'Rapunzel"s Companion', 'Character', 0, 0, 0.35, 1, 1, 1, 'The First Chapter'),
('Donald Duck', 'Boisterous Fowl', 'Character', 0, 0, 0.35, 2, 2, 3, 'The First Chapter'),
('Mad Hatter', 'Gracious Host', 'Character', 0, 0, 0.35, 5, 2, 4, 'The First Chapter'),
('Simba', 'Rightful Heir', 'Character', 0, 0, 0.35, 5, 3, 5, 'The First Chapter'),
('Sven', 'Official Ice Deliverer', 'Character', 0, 0, 0.35, 6, 5, 7, 'The First Chapter'),
('Coconut Basket', NULL, 'Item', 0, 0, 0.35, 2, NULL, NULL, 'The First Chapter'),
('Captain', 'Colonel"s Lieutenant', 'Character', 0, 0, 0.35, 5, 6, 5, 'The First Chapter'),
('Jasper', 'Common Crook', 'Character', 0, 0, 0.35, 3, 2, 4, 'The First Chapter'),
('Kronk', 'Right-Hand Man', 'Character', 0, 0, 0.35, 6, 6, 6, 'The First Chapter'),
('Starkey', 'Hook"s Henchman', 'Character', 0, 0, 0.35, 5, 5, 4, 'The First Chapter'),
('Reflection', NULL, 'Action', 0, 0, 0.35, 1, NULL, NULL, 'The First Chapter'),
('Dr. Facilier"s Cards', NULL, 'Item', 0, 0, 0.35, 2, NULL, NULL, 'The First Chapter'),
('Shield Of Virtue', NULL, 'Item', 0, 0, 0.35, 1, NULL, NULL, 'The First Chapter'),
('Donald Duck', 'Musketeer', 'Character', 0, 0, 0.35, 4, 2, 5, 'The First Chapter'),
('Tigger', 'Wonderful Thing', 'Character', 0, 0, 0.35, 6, 4, 4, 'The First Chapter'),
('Cinderella', 'Gentle and Kind', 'Character', 0, 0, 0.35, 4, 2, 5, 'The First Chapter'),
('Dragon Fire', NULL, 'Action', 0, 0, 0.35, 5, NULL, NULL, 'The First Chapter'),
('Mother Knows best', NULL, 'Action', 0, 0, 0.35, 3, NULL, NULL, 'The First Chapter'),
('Maximus', 'Relentless Pursuer', 'Character', 0, 0, 0.35, 3, 3, 3, 'The First Chapter'),
('Tamatoa', 'Drab Little Crab', 'Character', 0, 0, 0.35, 2, 1, 4, 'The First Chapter'),
('The Beast Is Mine!', NULL, 'Action', 0, 0, 0.35, 3, NULL, NULL, 'The First Chapter'),
('Anna', 'Heir to Arendelle', 'Character', 0, 0, 0.35, 4, 2, 4, 'The First Chapter'),
('Fan The Flames', NULL, 'Action', 0, 0, 0.35, 1, NULL, NULL, 'The First Chapter'),
('Aurora', 'Regal Princess', 'Character', 0, 0, 0.35, 2, 2, 2, 'The First Chapter'),
('Scepter Of Arendelle', NULL, 'Item', 0, 0, 0.35, 1, NULL, NULL, 'The First Chapter'),
('Scar', 'Fiery Usurper', 'Character', 0, 0, 0.25, 4, 5, 3, 'The First Chapter'),
('Sebastian', 'Court Composer', 'Character', 0, 0, 0.25, 2, 2, 2, 'The First Chapter'),
('Magic Broom', 'Bucket Brigade', 'Character', 0, 0, 0.25, 2, 2, 2, 'The First Chapter'),
('Peter Pan', 'Never Landing', 'Character', 0, 0, 0.25, 3, 3, 2, 'The First Chapter'),
('Mr. Smee', 'Loyal First Mate', 'Character', 0, 0, 0.25, 3, 2, 5, 'The First Chapter'),
('Jasmine', 'Disguised', 'Character', 0, 0, 0.25, 3, 3, 3, 'The First Chapter'),
('Tinker Bell', 'Tiny Tactician', 'Character', 0, 0, 0.25, 3, 2, 4, 'The First Chapter'),
('Tinker Bell', 'Peter Pan"s Ally', 'Character', 0, 0, 0.25, 5, 3, 3, 'The First Chapter'),
('Minnie Mouse', 'Beloved Princess', 'Character', 0, 0, 0.25, 2, 2, 3, 'The First Chapter'),
('Jetsam', 'Ursula"s Spy', 'Character', 0, 0, 0.25, 4, 3, 3, 'The First Chapter'),
('Stolen Scimitar', NULL, 'Item', 0, 0, 0.25, 2, NULL, NULL, 'The First Chapter'),
('Tangle', NULL, 'Action', 0, 0, 0.25, 2, NULL, NULL, 'The First Chapter'),
('The Wardrobe', 'Belle"s Confidant', 'Character', 0, 0, 0.25, 3, 3, 4, 'The First Chapter'),
('Prince Eric', 'Dashing and Brave', 'Character', 0, 0, 0.25, 2, 1, 3, 'The First Chapter'),
('Maleficent', 'Sinister Visitor', 'Character', 0, 0, 0.25, 4, 3, 4, 'The First Chapter'),
('Abu', 'Mischievous Monkey', 'Character', 0, 0, 0.25, 3, 3, 2, 'The First Chapter'),
('Megara', 'Pulling the Strings', 'Character', 0, 0, 0.25, 2, 2, 1, 'The First Chapter'),
('Break', NULL, 'Action', 0, 0, 0.25, 2, NULL, NULL, 'The First Chapter'),
('Aladdin', 'Street Rat', 'Character', 0, 0, 0.25, 3, 2, 2, 'The First Chapter'),
('Beast"s Mirror', NULL, 'Item', 0, 0, 0.25, 2, NULL, NULL, 'The First Chapter'),
('Control Your Temper!', NULL, 'Action', 0, 0, 0.25, 1, NULL, NULL, 'The First Chapter'),
('Magic Golden Flower', NULL, 'Item', 0, 0, 0.25, 1, NULL, NULL, 'The First Chapter'),
('Stitch', 'New Dog', 'Character', 0, 0, 0.25, 1, 2, 2, 'The First Chapter'),
('Sergeant Tibbs', 'Courageous Cat', 'Character', 0, 0, 0.25, 1, 2, 2, 'The First Chapter'),
('Develop Your Brain', NULL, 'Action', 0, 0, 0.25, 1, NULL, NULL, 'The First Chapter'),
('Healing Glow', NULL, 'Action', 0, 0, 0.25, 1, NULL, NULL, 'The First Chapter'),
('Stampede', NULL, 'Action', 0, 0, 0.25, 1, NULL, NULL, 'The First Chapter'),
('Sudden Chill', NULL, 'Action', 0, 0, 0.25, 2, NULL, NULL, 'The First Chapter'),
('Donald Duck', 'Strutting His Stuff', 'Character', 0, 0, 0.25, 5, 4, 3, 'The First Chapter'),
('Tinker Bell', 'Most Helpful', 'Character', 0, 0, 0.25, 4, 2, 3, 'The First Chapter'),
('Fire The Cannons', NULL, 'Action', 0, 0, 0.25, 1, NULL, NULL, 'The First Chapter'),
('Hankuna Matata', NULL, 'Action', 0, 0, 0.25, 4, NULL, NULL, 'The First Chapter'),
('Aladdin', 'Prince Ali', 'Character', 0, 0, 0.25, 2, 2, 2, 'The First Chapter'),
('Horace', 'No-Good Scoundrel', 'Character', 0, 0, 0.25, 3, 4, 3, 'The First Chapter'),
('Minnie Mouse', 'Always Classy', 'Character', 0, 0, 0.25, 1, 1, 3, 'The First Chapter'),
('Kristoff', 'Official Ice Master', 'Character', 0, 0, 0.25, 3, 3, 3, 'The First Chapter'),
('He"s Got A Sword', NULL, 'Action', 0, 0, 0.25, 1, NULL, NULL, 'The First Chapter'),
('Aladdin', 'Cornered Swordsman', 'Character', 0, 0, 0.25, 2, 2, 1, 'The First Chapter'),
('Jafar', 'Wicked Sorcerer', 'Character', 0, 0, 0.25, 4, 2, 5, 'The First Chapter'),
('Maleficent', 'Sorceress', 'Character', 0, 0, 0.25, 3, 2, 2, 'The First Chapter'),
('Friends On The Other Side', NULL, 'Action', 0, 0, 0.25, 3, NULL, NULL, 'The First Chapter'),
('Goofy', 'Daredevil', 'Character', 0, 0, 0.25, 5, 3, 4, 'The First Chapter'),
('Dr. Facilier', 'Charlatan', 'Character', 0, 0, 0.25, 2, 0, 4, 'The First Chapter'),
('Captain Hook', 'Forceful Duelist', 'Character', 0, 0, 0.25, 1, 1, 2, 'The First Chapter'),
('Pumbaa', 'Friendly Warthog', 'Character', 0, 0, 0.25, 4, 3, 5, 'The First Chapter'),
('Elsa', 'Queen Regent', 'Character', 0, 0, 0.25, 4, 4, 4, 'The First Chapter'),
('Genie', 'The Ever Impressive', 'Character', 0, 0, 0.25, 2, 2, 3, 'The First Chapter'),
('Simba', 'Future King', 'Character', 0, 0, 0.25, 1, 1, 2, 'The First Chapter'),
('Archimedes', 'Highly Educated Owl', 'Character', 0, 0, 0.25, 1, 2, 2, 'The First Chapter'),
('Goons', 'Maleficent"s Underlings', 'Character', 0, 0, 0.25, 1, 2, 2, 'The First Chapter'),
('Flounder', 'Voice of Reason', 'Character', 0, 0, 0.25, 1, 2, 2, 'The First Chapter'),
('Hercules', 'True Hero', 'Character', 0, 0, 0.25, 3, 3, 3, 'The First Chapter'),
('Pongo', 'Ol" Rascal', 'Character', 0, 0, 0.25, 4, 2, 3, 'The First Chapter'),
('Heihei', 'Boat Snack', 'Character', 0, 0, 0.25, 1, 1, 2, 'The First Chapter'),
('Vicious Betrayal', NULL, 'Action', 0, 0, 0.25, 1, NULL, NULL, 'The First Chapter'),
('Timon', 'Grub Rustler', 'Character', 0, 0, 0.25, 1, 1, 2, 'The First Chapter'),
('Simba', 'Protective Cub', 'Character', 0, 0, 0.25, 2, 2, 3, 'The First Chapter'),
('Mickey Mouse', 'Detective', 'Character', 0, 0, 0.25, 3, 1, 3, 'The First Chapter'),
('Duke Of Weselton', 'Opportunistic Official', 'Character', 0, 0, 0.25, 1, 2, 2, 'The First Chapter'),
('Elsa', 'Ice Surfer', 'Character', 0, 0, 0.25, 4, 3, 4, 'The First Chapter'),
('Philoctetes', 'Trainer of Heroes', 'Character', 0, 0, 0.25, 2, 3, 1, 'The First Chapter'),
('Gaston', 'Arrogant Hunter', 'Character', 0, 0, 0.25, 1, 1, 1, 'The First Chapter'),
('Cerberus', 'Three-Headed Dog', 'Character', 0, 0, 0.25, 5, 5, 6, 'The First Chapter'),
('Peter Pan', 'Fearless Fighter', 'Character', 0, 0, 0.25, 3, 3, 2, 'The First Chapter'),
('Aurora', 'Briar Rose', 'Character', 0, 0, 0.25, 4, 2, 5, 'The First Chapter'),
('Mufasa', 'King of the Pride', 'Character', 0, 0, 0.25, 6, 4, 6, 'The First Chapter'),
('Ymza', 'Alchemist', 'Character', 0, 0, 0.25, 2, 2, 2, 'The First Chapter'),
('Freeze', NULL, 'Action', 0, 0, 0.25, 2, NULL, NULL, 'The First Chapter'),
('Dinglehopper', NULL, 'Item', 0, 0, 0.25, 1, NULL, NULL, 'The First Chapter'),
('Mickey Mouse', 'Steamboat Pilot', 'Character', 0, 0, 0.25, 3, 3, 4, 'The First Chapter')